const faunaGenus = [
  { label: 'Anastomus (Striders', value: 'Anastomus' },
  { label: 'Anomalous (Exotic Biome Creatures)', value: 'Anomalous' },
  { label: 'Bos (Spiders)', value: 'Bos' },
  { label: 'Bosoptera (Crawling beetles)', value: 'Bosoptera' },
  { label: 'Conokinis (Swarming beetles)', value: 'Conokinis' },
  { label: 'Felidae (Cat)', value: 'Felidae' },
  { label: 'Felihex (Hexapodal cat)', value: 'Felihex' },
  { label: 'Hexungulatis (Hexapodal cow)', value: 'Hexungulatis' },
  { label: 'Lok (Blobs)', value: 'Lok' },
  { label: 'Mechanoceris (Robot)', value: 'Mechanoceris' },
  { label: 'Mogara (Proto-Gek)', value: 'Mogara' },
  { label: 'Osteofelidae (Bonecats)', value: 'Osteofelidae' },
  { label: 'Prionterrae (Ploughs)', value: 'Prionterrae' },
  { label: 'Procavya (Rodents)', value: 'Procavya' },
  { label: 'Protosphaeridae (Protorollers)', value: 'Protosphaeridae' },
  { label: 'Prototerrae (Protodiggers)', value: 'Prototerrae' },
  { label: 'Rangifae (Diplos)', value: 'Rangifae' },
  { label: 'Reococcyx (Bipedal antelopes)', value: 'Reococcyx' },
  { label: 'Spiralis (Drills)', value: 'Spiralis' },
  { label: 'Talpidae (Moles)', value: 'Talpidae' },
  { label: 'Tetraceris (Antelopes)', value: 'Tetraceris' },
  { label: 'Theroma (Triceratops)', value: 'Theroma' },
  { label: 'Tyranocae (Tyrannosaurus)', value: 'Tyranocae' },
  { label: 'Ungulatis (Cow)', value: 'Ungulatis' },
  { label: 'Procavaquatica (Swimming rodents)', value: 'Procavaquatica' },
  { label: 'Bosaquatica (Underwater crabs)', value: 'Bosaquatica' },
  { label: 'Chrysaora (Jellyfish)', value: 'Chrysaora' },
  { label: 'Ictaloris (Fish)', value: 'Ictaloris' },
  { label: 'Prionace (Sharks)', value: 'Prionace' },
  { label: 'Prionacefda (Swimming cows)', value: 'Prionacefda' },
  { label: 'Agnelis (Birds)', value: 'Agnelis' },
  { label: 'Cycromys (Dragons)', value: 'Cycromys' },
  { label: 'Oxyacta (Flying snakes)', value: 'Oxyacta' },
  { label: 'Protocaeli (Protoflyers)', value: 'Protocaeli' },
  { label: 'Rhopalocera (Butterflies)', value: 'Rhopalocera' }
];

export default faunaGenus;