const planetWeather = [
  { label: 'Temperate', value: 'Temperate' },
  { label: 'Boiling Puddles', value: 'Boiling Puddles' },
  { label: 'Boiling Superstorms', value: 'Boiling Superstorms' },
  { label: 'Light Showers', value: 'Light Showers' },
  { label: 'Sweltering Damp', value: 'Sweltering Damp' },
  { label: 'Intense Heatbursts', value: 'Intense Heatbursts' },
  { label: 'Mild Rain', value: 'Mild Rain' },
  { label: 'Superheated Drizzle', value: 'Superheated Drizzle' },
  { label: 'Superheated Rain', value: 'Superheated Rain' },
  { label: 'Refreshing Breeze', value: 'Refreshing Breeze' },
  { label: 'Dangerously Hot Fog', value: 'Dangerously Hot Fog' },
  { label: 'Boiling Monsoons', value: 'Boiling Monsoons' },
  { label: 'Humid', value: 'Humid' },
  { label: 'Choking Humidity', value: 'Choking Humidity' },
  { label: 'Broiling Humidity', value: 'Broiling Humidity' },
  { label: 'Pleasant', value: 'Pleasant' },
  { label: 'Mostly Calm', value: 'Mostly Calm' },
  { label: 'Painfully Hot Rain', value: 'Painfully Hot Rain' },
  { label: 'Balmy', value: 'Balmy' },
  { label: 'Occasional Scalding Cloudbursts', value: 'Occasional Scalding Cloudbursts' },
  { label: 'Torrential Heat', value: 'Torrential Heat' },
  { label: 'Mellow', value: 'Mellow' },
  { label: 'Usually Mild', value: 'Usually Mild' },
  { label: 'Blistering Floods', value: 'Blistering Floods' },
  { label: 'Beautiful', value: 'Beautiful' },
  { label: 'Blistering Damp', value: 'Blistering Damp' },
  { label: 'Scalding Rainstorms', value: 'Scalding Rainstorms' },
  { label: 'Blissful', value: 'Blissful' },
  { label: 'Lethal Humidity Outbreaks', value: 'Lethal Humidity Outbreaks' },
  { label: 'Torrid Deluges', value: 'Torrid Deluges' },
  { label: 'Baked', value: 'Baked' },
  { label: 'Blasted Atmosphere', value: 'Blasted Atmosphere' },
  { label: 'Billowing Dust Storms', value: 'Billowing Dust Storms' },
  { label: 'Clear', value: 'Clear' },
  { label: 'Ceaseless Drought', value: 'Ceaseless Drought' },
  { label: 'Dry Gusts', value: 'Dry Gusts' },
  { label: 'Dust-Choked Winds', value: 'Dust-Choked Winds' },
  { label: 'Choking Sandstorms', value: 'Choking Sandstorms' },
  { label: 'Icy Nights', value: 'Icy Nights' },
  { label: 'Freezing Night Winds', value: 'Freezing Night Winds' },
  { label: 'Dead Wastes', value: 'Dead Wastes' },
  { label: 'Moistureless', value: 'Moistureless' },
  { label: 'Highly Variable Temperatures', value: 'Highly Variable Temperatures' },
  { label: 'Extreme Wind Blasting', value: 'Extreme Wind Blasting' },
  { label: 'Sterile', value: 'Sterile' },
  { label: 'Infrequent Dust Storms', value: 'Infrequent Dust Storms' },
  { label: 'Hazardous Temperature Extremes', value: 'Hazardous Temperature Extremes' },
  { label: 'Unclouded Skies', value: 'Unclouded Skies' },
  { label: 'Intermittent Wind Blasting', value: 'Intermittent Wind Blasting' },
  { label: 'Howling Gales', value: 'Howling Gales' },
  { label: 'Withered', value: 'Withered' },
  { label: 'Occasional Sandstorms', value: 'Occasional Sandstorms' },
  { label: 'Lung-Burning Night Wind', value: 'Lung-Burning Night Wind' },
  { label: 'Parched Sands', value: 'Parched Sands' },
  { label: 'Planetwide Desiccation', value: 'Planetwide Desiccation' },
  { label: 'Sporadic Grit Storms', value: 'Sporadic Grit Storms' },
  { label: 'Sand Blizzards', value: 'Sand Blizzards' },
  { label: 'Absent', value: 'Absent' },
  { label: 'Airless', value: 'Airless' },
  { label: 'Eerily Calm', value: 'Eerily Calm' },
  { label: 'Inert', value: 'Inert' },
  { label: 'No Atmosphere', value: 'No Atmosphere' },
  { label: 'Peaceful', value: 'Peaceful' },
  { label: 'Perfectly Clear', value: 'Perfectly Clear' },
  { label: 'Silent', value: 'Silent' },
  { label: 'Utterly Still', value: 'Utterly Still' },
  { label: 'Invisible Mist', value: 'Invisible Mist' },
  { label: 'Internal Rain', value: 'Internal Rain' },
  { label: 'Lost Clouds', value: 'Lost Clouds' },
  { label: 'Crimson Heat', value: 'Crimson Heat' },
  { label: 'Winds of Glass', value: 'Winds of Glass' },
  { label: 'Thirsty Clouds', value: 'Thirsty Clouds' },
  { label: 'Obsidian Heat', value: 'Obsidian Heat' },
  { label: 'Memories of Frost', value: 'Memories of Frost' },
  { label: 'Haunted Frost', value: 'Haunted Frost' },
  { label: 'Indetectable Burning', value: 'Indetectable Burning' },
  { label: '[REDACTED]', value: '[REDACTED]' },
  { label: 'Anomalous', value: 'Anomalous' },
  { label: 'Burning Crimson', value: 'Burning Crimson' },
  { label: 'Bilious Storms', value: 'Bilious Storms' },
  { label: 'Frozen Mists', value: 'Frozen Mists' },
  { label: 'Scarlet Rain', value: 'Scarlet Rain' },
  { label: 'Deadly Pressure Variations', value: 'Deadly Pressure Variations' },
  { label: 'Electric Rain', value: 'Electric Rain' },
  { label: 'Fevered Clouds', value: 'Fevered Clouds' },
  { label: 'Harsh Toxic Wind', value: 'Harsh Toxic Wind' },
  { label: 'Azure Storms', value: 'Azure Storms' },
  { label: 'Carmine Winds', value: 'Carmine Winds' },
  { label: 'Corrupted Blood', value: 'Corrupted Blood' },
  { label: 'Extreme Low Pressure', value: 'Extreme Low Pressure' },
  { label: 'Red Mist', value: 'Red Mist' },
  { label: 'Infinite Toxic Mist', value: 'Infinite Toxic Mist' },
  { label: 'All-Consuming Cold', value: 'All-Consuming Cold' },
  { label: 'Flaming Hail', value: 'Flaming Hail' },
  { label: 'Echoes of Acid', value: 'Echoes of Acid' },
  { label: 'Winds from Beyond', value: 'Winds from Beyond' },
  { label: 'Vermillion Storms', value: 'Vermillion Storms' },
  { label: 'Poison Cyclones', value: 'Poison Cyclones' },
  { label: 'Unfathomable Storms', value: 'Unfathomable Storms' },
  { label: 'Rain of Atlas', value: 'Rain of Atlas' },
  { label: 'Inescapable Toxins', value: 'Inescapable Toxins' },
  { label: 'Unimaginable Blue', value: 'Unimaginable Blue' },
  { label: 'Angered Clouds', value: 'Angered Clouds' },
  { label: 'Clouds of Haunted Green', value: 'Clouds of Haunted Green' },
  { label: 'Ultramarine Wind', value: 'Ultramarine Wind' },
  { label: 'Blood Rain', value: 'Blood Rain' },
  { label: 'Invisible Jade Winds', value: 'Invisible Jade Winds' },
  { label: 'Inverted Superstorms', value: 'Inverted Superstorms' },
  { label: 'Parched', value: 'Parched' },
  { label: 'Infrequent Heat Storms', value: 'Infrequent Heat Storms' },
  { label: 'Extreme Heat', value: 'Extreme Heat' },
  { label: 'Overly Warm', value: 'Overly Warm' },
  { label: 'Rare Firestorms', value: 'Rare Firestorms' },
  { label: 'Burning Gas Clouds', value: 'Burning Gas Clouds' },
  { label: 'Sunny', value: 'Sunny' },
  { label: 'Superheated Gas Pockets', value: 'Superheated Gas Pockets' },
  { label: 'Intense Heat', value: 'Intense Heat' },
  { label: 'Dehydrated', value: 'Dehydrated' },
  { label: 'Wandering Hot Spots', value: 'Wandering Hot Spots' },
  { label: 'Superheated Air', value: 'Superheated Air' },
  { label: 'Unending Sunlight', value: 'Unending Sunlight' },
  { label: 'Atmospheric Heat Instabilities', value: 'Atmospheric Heat Instabilities' },
  { label: 'Scalding Heat', value: 'Scalding Heat' },
  { label: 'Direct Sunlight', value: 'Direct Sunlight' },
  { label: 'Inferno Winds', value: 'Inferno Winds' },
  { label: 'Heated Atmosphere', value: 'Heated Atmosphere' },
  { label: 'Firestorms', value: 'Firestorms' },
  { label: 'Sweltering', value: 'Sweltering' },
  { label: 'Occasional Ash Storms', value: 'Occasional Ash Storms' },
  { label: 'Combustible Dust', value: 'Combustible Dust' },
  { label: 'Dangerously Hot', value: 'Dangerously Hot' },
  { label: 'Incendiary Dust', value: 'Incendiary Dust' },
  { label: 'Burning Air', value: 'Burning Air' },
  { label: 'Self-Igniting Storms', value: 'Self-Igniting Storms' },
  { label: 'Crisp', value: 'Crisp' },
  { label: 'Drifting Snowstorms', value: 'Drifting Snowstorms' },
  { label: 'Deep Freeze', value: 'Deep Freeze' },
  { label: 'Freezing', value: 'Freezing' },
  { label: 'Frozen Clouds', value: 'Frozen Clouds' },
  { label: 'Frequent Blizzards', value: 'Frequent Blizzards' },
  { label: 'Frost', value: 'Frost' },
  { label: 'Harsh, Icy Winds', value: 'Harsh, Icy Winds' },
  { label: 'Hazardous Whiteouts', value: 'Hazardous Whiteouts' },
  { label: 'Icy', value: 'Icy' },
  { label: 'Icy Blasts', value: 'Icy Blasts' },
  { label: 'Howling Blizzards', value: 'Howling Blizzards' },
  { label: 'Permafrost', value: 'Permafrost' },
  { label: 'Ice Storms', value: 'Ice Storms' },
  { label: 'Icy Tempests', value: 'Icy Tempests' },
  { label: 'Powder Snow', value: 'Powder Snow' },
  { label: 'Infrequent Blizzards', value: 'Infrequent Blizzards' },
  { label: 'Snowy', value: 'Snowy' },
  { label: 'Migratory Blizzards', value: 'Migratory Blizzards' },
  { label: 'Intense Cold', value: 'Intense Cold' },
  { label: 'Wintry', value: 'Wintry' },
  { label: 'Occasional Snowfall', value: 'Occasional Snowfall' },
  { label: 'Raging Snowstorms', value: 'Raging Snowstorms' },
  { label: 'Outbreaks of Frozen Rain', value: 'Outbreaks of Frozen Rain' },
  { label: 'Roaring Ice Storms', value: 'Roaring Ice Storms' },
  { label: 'Wandering Frosts', value: 'Wandering Frosts' },
  { label: 'Supercooled Storms', value: 'Supercooled Storms' },
  { label: 'Acid Rain', value: 'Acid Rain' },
  { label: 'Acidic Dust Pockets', value: 'Acidic Dust Pockets' },
  { label: 'Acidic Deluges', value: 'Acidic Deluges' },
  { label: 'Caustic Moisture', value: 'Caustic Moisture' },
  { label: 'Alkaline Cloudbursts', value: 'Alkaline Cloudbursts' },
  { label: 'Bone-Stripping Acid Storms', value: 'Bone-Stripping Acid Storms' },
  { label: 'Choking Clouds', value: 'Choking Clouds' },
  { label: 'Atmospheric Corruption', value: 'Atmospheric Corruption' },
  { label: 'Caustic Floods', value: 'Caustic Floods' },
  { label: 'Corrosive Damp', value: 'Corrosive Damp' },
  { label: 'Caustic Winds', value: 'Caustic Winds' },
  { label: 'Corrosive Cyclones', value: 'Corrosive Cyclones' },
  { label: 'Poison Rain', value: 'Poison Rain' },
  { label: 'Corrosive Sleet Storms', value: 'Corrosive Sleet Storms' },
  { label: 'Corrosive Rainstorms', value: 'Corrosive Rainstorms' },
  { label: 'Poisonous Gas', value: 'Poisonous Gas' },
  { label: 'Dangerously Toxic Rain', value: 'Dangerously Toxic Rain' },
  { label: 'Corrosive Storms', value: 'Corrosive Storms' },
  { label: 'Stinging Atmosphere', value: 'Stinging Atmosphere' },
  { label: 'Infrequent Toxic Drizzle', value: 'Infrequent Toxic Drizzle' },
  { label: 'Frequent Toxic Floods', value: 'Frequent Toxic Floods' },
  { label: 'Stinging Puddles', value: 'Stinging Puddles' },
  { label: 'Lethal Atmosphere', value: 'Lethal Atmosphere' },
  { label: 'Noxious Gas Storms', value: 'Noxious Gas Storms' },
  { label: 'Toxic Clouds', value: 'Toxic Clouds' },
  { label: 'Occasional Acid Storms', value: 'Occasional Acid Storms' },
  { label: 'Pouring Toxic Rain', value: 'Pouring Toxic Rain' },
  { label: 'Toxic Damp', value: 'Toxic Damp' },
  { label: 'Passing Toxic Fronts', value: 'Passing Toxic Fronts' },
  { label: 'Torrential Acid', value: 'Torrential Acid' },
  { label: 'Poison Flurries', value: 'Poison Flurries' },
  { label: 'Toxic Monsoons', value: 'Toxic Monsoons' },
  { label: 'Toxic Outbreaks', value: 'Toxic Outbreaks' },
  { label: 'Toxic Superstorms', value: 'Toxic Superstorms' },
  { label: 'Contaminated Puddles', value: 'Contaminated Puddles' },
  { label: 'Energetic Storms', value: 'Energetic Storms' },
  { label: 'Contaminated Squalls', value: 'Contaminated Squalls' },
  { label: 'Gamma Dust', value: 'Gamma Dust' },
  { label: 'Irradiated Downpours', value: 'Irradiated Downpours' },
  { label: 'Enormous Nuclear Storms', value: 'Enormous Nuclear Storms' },
  { label: 'Irradiated Winds', value: 'Irradiated Winds' },
  { label: 'Irradiated Storms', value: 'Irradiated Storms' },
  { label: 'Extreme Atmospheric Decay', value: 'Extreme Atmospheric Decay' },
  { label: 'Nuclidic Atmosphere', value: 'Nuclidic Atmosphere' },
  { label: 'Occasional Radiation Outbursts', value: 'Occasional Radiation Outbursts' },
  { label: 'Extreme Radioactivity', value: 'Extreme Radioactivity' },
  { label: 'Radioactive Damp', value: 'Radioactive Damp' },
  { label: 'Particulate Winds', value: 'Particulate Winds' },
  { label: 'Extreme Thermonuclear Fog', value: 'Extreme Thermonuclear Fog' },
  { label: 'Radioactive Humidity', value: 'Radioactive Humidity' },
  { label: 'Radioactive Dust Storms', value: 'Radioactive Dust Storms' },
  { label: 'Frequent Particle Eruptions', value: 'Frequent Particle Eruptions' },
  { label: 'Unstable Atmosphere', value: 'Unstable Atmosphere' },
  { label: 'Reactive Rain', value: 'Reactive Rain' },
  { label: 'Gamma Cyclones', value: 'Gamma Cyclones' },
  { label: 'Volatile Winds', value: 'Volatile Winds' },
  { label: 'Unstable Fog', value: 'Unstable Fog' },
  { label: 'Irradiated Thunderstorms', value: 'Irradiated Thunderstorms' },
  { label: 'Volatile Windstorms', value: 'Volatile Windstorms' },
  { label: 'Planet-Wide Radiation Storms', value: 'Planet-Wide Radiation Storms' },
  { label: 'Roaring Nuclear Wind', value: 'Roaring Nuclear Wind' },
  { label: 'Gentle Mist', value: 'Gentle Mist' },
  { label: 'Tropical Storms', value: 'Tropical Storms' },
  { label: 'Death Fog', value: 'Death Fog' },
  { label: 'Occasional Boiling Fog', value: 'Occasional Boiling Fog' },
  { label: 'Sultry Disaster', value: 'Sultry Disaster' },
  { label: 'Tropical Winds', value: 'Tropical Winds' },
  { label: 'Superheated Mists', value: 'Superheated Mists' },
  { label: 'Cataclysmic Monsoons', value: 'Cataclysmic Monsoons' },
  { label: 'Warm Fog', value: 'Warm Fog' },
  { label: 'Painful Mist', value: 'Painful Mist' },
  { label: 'Mists of Annihilation', value: 'Mists of Annihilation' },
  { label: 'Temperate Murk', value: 'Temperate Murk' },
  { label: 'Infrequent Torrents', value: 'Infrequent Torrents' },
  { label: 'All-Consuming Fog', value: 'All-Consuming Fog' },
  { label: 'Mild Damp', value: 'Mild Damp' },
  { label: 'Oppressive', value: 'Oppressive' },
  { label: 'Liquid Hell', value: 'Liquid Hell' },
  { label: 'Warm Dewdrops', value: 'Warm Dewdrops' },
  { label: 'Soggy Danger', value: 'Soggy Danger' },
  { label: 'Storms of Desolation', value: 'Storms of Desolation' },
  { label: 'Tepid Damp', value: 'Tepid Damp' },
  { label: 'Sticky Heat', value: 'Sticky Heat' },
  { label: 'Melting Deluges', value: 'Melting Deluges' },
  { label: 'Sweaty Drizzle', value: 'Sweaty Drizzle' },
  { label: 'Clammy Menace', value: 'Clammy Menace' },
  { label: 'Boiling Catastrophe', value: 'Boiling Catastrophe' },
  { label: 'Muggy Haze', value: 'Muggy Haze' },
  { label: 'Hazardous Moisture', value: 'Hazardous Moisture' },
  { label: 'Damp Misery', value: 'Damp Misery' },
  { label: 'Sulphurous Haze', value: 'Sulphurous Haze' },
  { label: 'Heated Gas Pockets', value: 'Heated Gas Pockets' },
  { label: 'Frequent Firestorms', value: 'Frequent Firestorms' },
  { label: 'Ash Wisps', value: 'Ash Wisps' },
  { label: 'Occasional Firestorms', value: 'Occasional Firestorms' },
  { label: 'Walls of Flame', value: 'Walls of Flame' },
  { label: 'Drifting Smog', value: 'Drifting Smog' },
  { label: 'Incendiary Winds', value: 'Incendiary Winds' },
  { label: 'Clouds of Fire', value: 'Clouds of Fire' },
  { label: 'Cinderfalls', value: 'Cinderfalls' },
  { label: 'Unpredictable Conflagrations', value: 'Unpredictable Conflagrations' },
  { label: 'Ashen Destruction', value: 'Ashen Destruction' },
  { label: 'Ash Plumes', value: 'Ash Plumes' },
  { label: 'Drifting Firestorms', value: 'Drifting Firestorms' },
  { label: 'Magma Rain', value: 'Magma Rain' },
  { label: 'Choking Ash', value: 'Choking Ash' },
  { label: 'Pillars of Flame', value: 'Pillars of Flame' },
  { label: 'Basalt Hail', value: 'Basalt Hail' },
  { label: 'Burning Mists', value: 'Burning Mists' },
  { label: 'Magma Geysers', value: 'Magma Geysers' },
  { label: 'Explosive Gas Eruptions', value: 'Explosive Gas Eruptions' },
  { label: 'Sulfur Fumes', value: 'Sulfur Fumes' },
  { label: 'Plumes of Fire', value: 'Plumes of Fire' },
  { label: 'Lethal Ash Storms', value: 'Lethal Ash Storms' },
  { label: 'Enveloping Ash', value: 'Enveloping Ash' },
  { label: 'Molten Rain', value: 'Molten Rain' },
  { label: 'Sulphurous Inferno', value: 'Sulphurous Inferno' },
  { label: 'Ashen Winds', value: 'Ashen Winds' },
  { label: 'Tectonic Storms', value: 'Tectonic Storms' },
  { label: 'Colossal Firestorms', value: 'Colossal Firestorms' },
  { label: 'Smothering Ash', value: 'Smothering Ash' },
  { label: 'Obsidian Doom', value: 'Obsidian Doom' }
];

export default planetWeather;
