const systemEconomy = [
  { value: 'Mercantile', label: 'Mercantile' },
  { value: 'Trading', label: 'Trading' },
  { value: 'Shipping', label: 'Shipping' },
  { value: 'Commercial', label: 'Commercial' },
  { value: 'Material Fusion', label: 'Material Fusion' },
  { value: 'Alchemical', label: 'Alchemical' },
  { value: 'Metal Processing', label: 'Metal Processing' },
  { value: 'Ore Processing', label: 'Ore Processing' },
  { value: 'Research', label: 'Research' },
  { value: 'Scientific', label: 'Scientific' },
  { value: 'Experimental', label: 'Experimental' },
  { value: 'Mathematical', label: 'Mathematical' },
  { value: 'Mining', label: 'Mining' },
  { value: 'Minerals', label: 'Minerals' },
  { value: 'Ore Extraction', label: 'Ore Extraction' },
  { value: 'Prospecting', label: 'Prospecting' },
  { value: 'Manufacturing', label: 'Manufacturing' },
  { value: 'Industrial', label: 'Industrial' },
  { value: 'Construction', label: 'Construction' },
  { value: 'Mass Production', label: 'Mass Production' },
  { value: 'High Tech', label: 'High Tech' },
  { value: 'Technology', label: 'Technology' },
  { value: 'Nano-construction', label: 'Nano-construction' },
  { value: 'Engineering', label: 'Engineering' },
  { value: 'Power Generation', label: 'Power Generation' },
  { value: 'Energy Supply', label: 'Energy Supply' },
  { value: 'Fuel Generation', label: 'Fuel Generation' },
  { value: 'High Voltage', label: 'High Voltage' }
];

export default systemEconomy;